# Generated by Django 5.2.3 on 2025-09-14 07:45

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        max_length=150, unique=True, verbose_name="用户名"
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="密码")),
                (
                    "sex",
                    models.CharField(
                        choices=[("m", "男"), ("f", "女")],
                        default="m",
                        max_length=1,
                        verbose_name="性别",
                    ),
                ),
                ("introduction", models.TextField(verbose_name="个性签名")),
                ("avatar", models.ImageField(upload_to="avatar/", verbose_name="头像")),
                (
                    "email",
                    models.EmailField(max_length=254, unique=True, verbose_name="邮箱"),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户",
                "verbose_name_plural": "用户",
                "db_table": "user",
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="User_Drone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("delivery_count_january", models.IntegerField(default=0)),
                ("success_count_january", models.IntegerField(default=0)),
                ("delivery_count_february", models.IntegerField(default=0)),
                ("success_count_february", models.IntegerField(default=0)),
                ("delivery_count_march", models.IntegerField(default=0)),
                ("success_count_march", models.IntegerField(default=0)),
                ("delivery_count_april", models.IntegerField(default=0)),
                ("success_count_april", models.IntegerField(default=0)),
                ("delivery_count_may", models.IntegerField(default=0)),
                ("success_count_may", models.IntegerField(default=0)),
                ("delivery_count_june", models.IntegerField(default=0)),
                ("success_count_june", models.IntegerField(default=0)),
                ("delivery_count_july", models.IntegerField(default=0)),
                ("success_count_july", models.IntegerField(default=0)),
                ("delivery_count_august", models.IntegerField(default=0)),
                ("success_count_august", models.IntegerField(default=0)),
                ("delivery_count_september", models.IntegerField(default=0)),
                ("success_count_september", models.IntegerField(default=0)),
                ("delivery_count_october", models.IntegerField(default=0)),
                ("success_count_october", models.IntegerField(default=0)),
                ("delivery_count_november", models.IntegerField(default=0)),
                ("success_count_november", models.IntegerField(default=0)),
                ("delivery_count_december", models.IntegerField(default=0)),
                ("success_count_december", models.IntegerField(default=0)),
                (
                    "username",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "使用次数",
                "verbose_name_plural": "使用次数",
                "db_table": "user_drone",
            },
        ),
        migrations.CreateModel(
            name="YearlyUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField()),
                ("emergency", models.IntegerField(default=0)),
                ("women", models.IntegerField(default=0)),
                ("traditional_chinese", models.IntegerField(default=0)),
                ("chronic_disease", models.IntegerField(default=0)),
                ("medical_aesthetics", models.IntegerField(default=0)),
                (
                    "username",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "年度使用药品数量",
                "verbose_name_plural": "年度使用药品数量",
                "db_table": "yearly_usage",
            },
        ),
        migrations.CreateModel(
            name="YearlyFailure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveSmallIntegerField()),
                ("total", models.PositiveIntegerField(default=0)),
                ("weather", models.PositiveIntegerField(default=0)),
                ("battery", models.PositiveIntegerField(default=0)),
                ("navigation", models.PositiveIntegerField(default=0)),
                ("airspace", models.PositiveIntegerField(default=0)),
                ("others", models.PositiveIntegerField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "年度失败原因",
                "verbose_name_plural": "年度失败原因",
                "db_table": "yearly_failures",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "year"), name="unique_user_year"
                    )
                ],
            },
        ),
    ]
