# Generated by Django 5.2.3 on 2025-11-03 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("shop_app", "0005_remove_comment_avatar"),
    ]

    operations = [
        migrations.CreateModel(
            name="Hospital",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("longitude", models.FloatField()),
                ("latitude", models.FloatField()),
            ],
            options={
                "verbose_name": "配送站点",
                "verbose_name_plural": "配送站点",
                "db_table": "hospital",
            },
        ),
        migrations.CreateModel(
            name="HospitalInventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(default=0)),
                (
                    "hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="route_app.hospital",
                    ),
                ),
                (
                    "medicine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shop_app.medicine",
                    ),
                ),
            ],
            options={
                "verbose_name": "医院库存",
                "verbose_name_plural": "医院库存",
                "db_table": "hospital_inventory",
                "unique_together": {("hospital", "medicine")},
            },
        ),
    ]
