# Generated by Django 5.2.3 on 2025-11-07 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nickname", models.CharField(default="匿名用户", max_length=50)),
                ("order_id", models.CharField(max_length=50)),
                ("name", models.CharField(max_length=50)),
                ("phone", models.CharField(max_length=50)),
                ("address", models.CharField(max_length=100)),
                ("province", models.CharField(max_length=50)),
                ("city", models.CharField(max_length=50)),
                ("order_time", models.DateTimeField()),
                ("latitude", models.FloatField(default=0.0)),
                ("longitude", models.FloatField(default=0.0)),
                ("district", models.CharField(max_length=50)),
                ("notes", models.TextField(blank=True)),
                ("paymentMethod", models.CharField(max_length=50)),
                ("items", models.JSONField()),
                ("status", models.CharField(default="送货中", max_length=50)),
            ],
            options={
                "verbose_name": "订单",
                "verbose_name_plural": "订单",
                "db_table": "order",
            },
        ),
    ]
