# Generated by Django 5.2.3 on 2025-11-07 03:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pay_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_time",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
