# Generated by Django 5.2.3 on 2025-11-07 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pay_app", "0002_alter_order_order_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_time",
            field=models.DateTimeField(default=1762487569.5582361),
        ),
    ]
