USE plane_in_medical;

UPDATE medicine SET kind='中药', name='板蓝根颗粒', image='http://t5wj9b45v.hn-bkt.clouddn.com/medicine/medicine_001.png', introduction='清热解毒，预防流感', price=18.5 WHERE id=1;
UPDATE medicine SET kind='西药', name='布洛芬缓释胶囊', image='http://t5wj9b45v.hn-bkt.clouddn.com/medicine/medicine_002.png', introduction='退烧止痛，一丸见效', price=25.0 WHERE id=2;
UPDATE medicine SET kind='保健品', name='维生素C泡腾片', image='http://t5wj9b45v.hn-bkt.clouddn.com/medicine/medicine_003.png', introduction='每日一片，增强抵抗力', price=32.8 WHERE id=3;
UPDATE medicine SET kind='医疗器械', name='电子体温计', image='http://t5wj9b45v.hn-bkt.clouddn.com/medicine/medicine_004.png', introduction='秒测体温，高温蜂鸣提醒', price=49.9 WHERE id=4;
UPDATE medicine SET kind='防疫用品', name='医用外科口罩', image='http://t5wj9b45v.hn-bkt.clouddn.com/medicine/medicine_005.png', introduction='三层过滤，细菌过滤率≥98%', price=19.9 WHERE id=5;
UPDATE medicine SET kind='中药', name='连花清瘟胶囊', image='http://t5wj9b45v.hn-bkt.clouddn.com/medicine/medicine_006.png', introduction='抗击流感，缓解咳嗽', price=29.7 WHERE id=6;
UPDATE medicine SET kind='西药', name='对乙酰氨基酚片', image='http://t5wj9b45v.hn-bkt.clouddn.com/medicine/medicine_007.png', introduction='快速退烧，儿童可用', price=15.2 WHERE id=7;
UPDATE medicine SET kind='保健品', name='鱼油软胶囊', image='http://t5wj9b45v.hn-bkt.clouddn.com/medicine/medicine_008.png', introduction='保护心脑血管，每粒含DHA3medicine_00mg', price=78.0 WHERE id=8;
UPDATE medicine SET kind='医疗器械', name='血糖仪套装', image='http://t5wj9b45v.hn-bkt.clouddn.com/medicine/medicine_009.png', introduction='家用免调码，5秒出结果', price=128.5 WHERE id=9;
UPDATE medicine SET kind='防疫用品', name='免洗手消毒凝胶', image='http://t5wj9b45v.hn-bkt.clouddn.com/medicine/medicine_010.png', introduction='75%酒精，搓手10秒速干', price=12.5 WHERE id=10;
UPDATE medicine SET kind='中药', name='藿香正气水', image='http://t5wj9b45v.hn-bkt.clouddn.com/medicine/medicine_011.png', introduction='防暑解暑，晕车晕船必备', price=21.3 WHERE id=11;
UPDATE medicine SET kind='西药', name='复方氨酚烷胺片', image='http://t5wj9b45v.hn-bkt.clouddn.com/medicine/medicine_012.png', introduction='感冒复方制剂，缓解鼻塞头痛', price=23.4 WHERE id=12;
UPDATE medicine SET kind='保健品', name='钙镁锌咀嚼片', image='http://t5wj9b45v.hn-bkt.clouddn.com/medicine/medicine_013.png', introduction='儿童成长三合一，香甜橙子味', price=38.6 WHERE id=13;
UPDATE medicine SET kind='医疗器械', name='雾化器', image='http://t5wj9b45v.hn-bkt.clouddn.com/medicine/medicine_014.png', introduction='微米级雾化，静音家用', price=156.8 WHERE id=14;
UPDATE medicine SET kind='防疫用品', name='防护服', image='http://t5wj9b45v.hn-bkt.clouddn.com/medicine/medicine_015.png', introduction='一次性医用，透气隔菌', price=45.0 WHERE id=15;
UPDATE medicine SET kind='中药', name='金银花露', image='http://t5wj9b45v.hn-bkt.clouddn.com/medicine/medicine_016.png', introduction='清热解毒，小儿亦可口服', price=16.6 WHERE id=16;
UPDATE medicine SET kind='西药', name='奥美拉唑肠溶胶囊', image='http://t5wj9b45v.hn-bkt.clouddn.com/medicine/medicine_017.png', introduction='抑制胃酸，胃痛克星', price=32.2 WHERE id=17;
UPDATE medicine SET kind='保健品', name='益生菌粉', image='http://t5wj9b45v.hn-bkt.clouddn.com/medicine/medicine_018.png', introduction='调节肠道菌群，改善便秘', price=68.9 WHERE id=18;
UPDATE medicine SET kind='医疗器械', name='颈椎牵引器', image='http://t5wj9b45v.hn-bkt.clouddn.com/medicine/medicine_019.png', introduction='充气式，办公室午休神器', price=89.9 WHERE id=19;
UPDATE medicine SET kind='防疫用品', name='抗原检测试剂', image='http://t5wj9b45v.hn-bkt.clouddn.com/medicine/medicine_020.png', introduction='15分钟自测，居家方便', price=9.9 WHERE id=20;
UPDATE medicine SET kind='中药', name='川贝枇杷膏', image='http://t5wj9b45v.hn-bkt.clouddn.com/medicine/021.png', introduction='润肺止咳，甜而不腻', price=35.5 WHERE id=21;
UPDATE medicine SET kind='西药', name='氯雷他定片', image='http://t5wj9b45v.hn-bkt.clouddn.com/medicine/medicine_022.png', introduction='一片缓解过敏鼻炎', price=17.8 WHERE id=22;
UPDATE medicine SET kind='保健品', name='叶黄素酯片', image='http://t5wj9b45v.hn-bkt.clouddn.com/medicine/medicine_023.png', introduction='过滤蓝光，缓解眼疲劳', price=56.0 WHERE id=23;
UPDATE medicine SET kind='医疗器械', name='按摩椅垫', image='http://t5wj9b45v.hn-bkt.clouddn.com/medicine/medicine_024.png', introduction='办公室午休神器', price=76.5 WHERE id=24;
UPDATE medicine SET kind='防疫用品', name='N95口罩', image='http://t5wj9b45v.hn-bkt.clouddn.com/medicine/medicine_025.png', introduction='KN95级别，双层熔喷布', price=28.8 WHERE id=25;
UPDATE medicine SET kind='中药', name='胖大海含片', image='http://t5wj9b45v.hn-bkt.clouddn.com/medicine/026.png', introduction='教师主播护嗓必备', price=13.3 WHERE id=26;
UPDATE medicine SET kind='西药', name='阿莫西林胶囊', image='http://t5wj9b45v.hn-bkt.clouddn.com/medicine/medicine_027.png', introduction='广谱抗菌，遵医嘱服用', price=24.6 WHERE id=27;
UPDATE medicine SET kind='保健品', name='胶原蛋白肽', image='http://t5wj9b45v.hn-bkt.clouddn.com/medicine/medicine_028.png', introduction='小分子易吸收，喝出弹润', price=98.2 WHERE id=28;
UPDATE medicine SET kind='医疗器械', name='家用制氧机', image='http://t5wj9b45v.hn-bkt.clouddn.com/medicine/medicine_029.png', introduction='1-7L可调，老人孕妇都适用', price=189.0 WHERE id=29;
UPDATE medicine SET kind='防疫用品', name='鞋套', image='http://t5wj9b45v.hn-bkt.clouddn.com/medicine/medicine_030.png', introduction='一次性防滑，无尘车间可用', price=8.8 WHERE id=30;
UPDATE medicine SET kind='中药', name='罗汉果茶', image='http://t5wj9b45v.hn-bkt.clouddn.com/medicine/031.png', introduction='零糖润喉，抽烟人士常备', price=19.9 WHERE id=31;
UPDATE medicine SET kind='西药', name='甲硝唑片', image='http://t5wj9b45v.hn-bkt.clouddn.com/medicine/032.png', introduction='抗厌氧菌，口腔消炎', price=11.2 WHERE id=32;
UPDATE medicine SET kind='保健品', name='奶蓟草片', image='http://t5wj9b45v.hn-bkt.clouddn.com/medicine/033.png', introduction='熬夜护肝，酒局必备', price=66.6 WHERE id=33;
UPDATE medicine SET kind='医疗器械', name='医用胶带', image='http://t5wj9b45v.hn-bkt.clouddn.com/medicine/034.png', introduction='低致敏，撕下无痛', price=6.5 WHERE id=34;
UPDATE medicine SET kind='防疫用品', name='面罩', image='http://t5wj9b45v.hn-bkt.clouddn.com/medicine/035.png', introduction='防飞沫，高清防雾', price=12.0 WHERE id=35;
UPDATE medicine SET kind='中药', name='当归片', image='http://t5wj9b45v.hn-bkt.clouddn.com/medicine/036.png', introduction='补血活血，煲汤泡酒皆宜', price=26.8 WHERE id=36;
UPDATE medicine SET kind='西药', name='布地奈德鼻喷雾', image='http://t5wj9b45v.hn-bkt.clouddn.com/medicine/037.png', introduction='过敏性鼻炎，一喷通畅', price=42.3 WHERE id=37;
UPDATE medicine SET kind='保健品', name='硒片', image='http://t5wj9b45v.hn-bkt.clouddn.com/medicine/038.png', introduction='提高免疫力，每日仅需50μg', price=48.8 WHERE id=38;
UPDATE medicine SET kind='医疗器械', name='轮椅坐垫', image='http://t5wj9b45v.hn-bkt.clouddn.com/medicine/039.png', introduction='减压防褥疮，透气记忆棉', price=87.4 WHERE id=39;
UPDATE medicine SET kind='防疫用品', name='体温枪', image='http://t5wj9b45v.hn-bkt.clouddn.com/medicine/040.png', introduction='非接触1秒测温，高温红灯警示', price=59.9 WHERE id=40;
UPDATE medicine SET kind='中药', name='艾草足贴', image='http://t5wj9b45v.hn-bkt.clouddn.com/medicine/041.png', introduction='睡前一贴，祛湿助眠', price=22.2 WHERE id=41;
UPDATE medicine SET kind='西药', name='西地碘含片', image='http://t5wj9b45v.hn-bkt.clouddn.com/medicine/042.png', introduction='口腔溃疡，含服止痛', price=18.4 WHERE id=42;
UPDATE medicine SET kind='保健品', name='左旋肉碱胶囊', image='http://t5wj9b45v.hn-bkt.clouddn.com/medicine/043.png', introduction='运动加速燃脂，0 咖啡因', price=55.5 WHERE id=43;
UPDATE medicine SET kind='医疗器械', name='静脉曲张袜', image='http://t5wj9b45v.hn-bkt.clouddn.com/medicine/044.png', introduction='医用一级压力，久站福音', price=69.9 WHERE id=44;
UPDATE medicine SET kind='防疫用品', name='酒精棉片', image='http://t5wj9b45v.hn-bkt.clouddn.com/medicine/045.png', introduction='独立包装，擦手机键盘', price=5.5 WHERE id=45;
UPDATE medicine SET kind='中药', name='枸杞原浆', image='http://t5wj9b45v.hn-bkt.clouddn.com/medicine/046.png', introduction='宁夏头茬鲜榨，明目抗疲劳', price=39.9 WHERE id=46;
UPDATE medicine SET kind='西药', name='雷贝拉唑钠片', image='http://t5wj9b45v.hn-bkt.clouddn.com/medicine/047.png', introduction='胃痛反酸，晨起空腹一片', price=36.7 WHERE id=47;
UPDATE medicine SET kind='保健品', name='GABA 软糖', image='http://t5wj9b45v.hn-bkt.clouddn.com/medicine/048.png', introduction='减压助眠，樱桃味 Q 弹', price=44.4 WHERE id=48;
UPDATE medicine SET kind='医疗器械', name='指夹式血氧仪', image='http://t5wj9b45v.hn-bkt.clouddn.com/medicine/049.png', introduction='8 秒测血氧，小巧随身', price=79.0 WHERE id=49;
UPDATE medicine SET kind='防疫用品', name='一次性帽子', image='http://t5wj9b45v.hn-bkt.clouddn.com/medicine/050.png', introduction='无纺布防尘，厨房也能用', price=7.7 WHERE id=50;
UPDATE medicine SET kind='中药', name='决明子茶', image='http://t5wj9b45v.hn-bkt.clouddn.com/medicine/051.png', introduction='清肝明目，久坐电脑党', price=21.0 WHERE id=51;
UPDATE medicine SET kind='西药', name='氟桂利嗪胶囊', image='http://t5wj9b45v.hn-bkt.clouddn.com/medicine/052.png', introduction='偏头痛预防，睡前服用', price=29.3 WHERE id=52;
UPDATE medicine SET kind='保健品', name='玻尿酸口服液', image='http://t5wj9b45v.hn-bkt.clouddn.com/medicine/053.png', introduction='补水锁水，喝出水光肌', price=89.9 WHERE id=53;
UPDATE medicine SET kind='医疗器械', name='冷敷凝胶', image='http://t5wj9b45v.hn-bkt.clouddn.com/medicine/054.png', introduction='扭伤退烧，物理降温 8h', price=15.6 WHERE id=54;
UPDATE medicine SET kind='防疫用品', name='消毒湿巾', image='http://t5wj9b45v.hn-bkt.clouddn.com/medicine/055.png', introduction='大包装 80 抽，杀新冠 99.9%', price=19.5 WHERE id=55;
UPDATE medicine SET kind='中药', name='茯苓饼', image='http://t5wj9b45v.hn-bkt.clouddn.com/medicine/056.png', introduction='健脾祛湿，北京老字号', price=18.8 WHERE id=56;
UPDATE medicine SET kind='西药', name='对乙酰氨基酚栓', image='http://t5wj9b45v.hn-bkt.clouddn.com/medicine/057.png', introduction='儿童退烧，肛门给药不呕吐', price=20.1 WHERE id=57;
UPDATE medicine SET kind='保健品', name='蔓越莓胶囊', image='http://t5wj9b45v.hn-bkt.clouddn.com/medicine/058.png', introduction='女性泌尿道守护，高原花青素', price=62.3 WHERE id=58;
UPDATE medicine SET kind='医疗器械', name='腰椎支撑靠垫', image='http://t5wj9b45v.hn-bkt.clouddn.com/medicine/059.png', introduction='记忆棉蝶形，开车办公护腰', price=95.2 WHERE id=59;
UPDATE medicine SET kind='防疫用品', name='护目镜', image='http://t5wj9b45v.hn-bkt.clouddn.com/medicine/060.png', introduction='防飞溅防粉尘，可戴近视镜', price=14.4 WHERE id=60;
UPDATE medicine SET kind='中药', name='陈皮普洱茶', image='http://t5wj9b45v.hn-bkt.clouddn.com/medicine/061.png', introduction='理气健脾，饭后消食', price=33.3 WHERE id=61;
UPDATE medicine SET kind='西药', name='复方甘草片', image='http://t5wj9b45v.hn-bkt.clouddn.com/medicine/062.png', introduction='镇咳祛痰，含服缓慢融化', price=9.9 WHERE id=62;
UPDATE medicine SET kind='保健品', name='维生素D3滴剂', image='http://t5wj9b45v.hn-bkt.clouddn.com/medicine/063.png', introduction='婴儿骨骼发育，每日 4medicine_00IU', price=35.0 WHERE id=63;
UPDATE medicine SET kind='医疗器械', name='止血贴', image='http://t5wj9b45v.hn-bkt.clouddn.com/medicine/064.png', introduction='弹性布基，防水洗澡', price=8.3 WHERE id=64;
UPDATE medicine SET kind='防疫用品', name='一次性手套', image='http://t5wj9b45v.hn-bkt.clouddn.com/medicine/065.png', introduction='丁腈无粉，耐穿刺', price=22.7 WHERE id=65;
UPDATE medicine SET kind='中药', name='黄芪精', image='http://t5wj9b45v.hn-bkt.clouddn.com/medicine/066.png', introduction='补气固表，易拉瓶即饮', price=40.4 WHERE id=66;
UPDATE medicine SET kind='西药', name='盐酸氨溴索口服液', image='http://t5wj9b45v.hn-bkt.clouddn.com/medicine/067.png', introduction='稀释痰液，儿童草莓味', price=24.9 WHERE id=67;
UPDATE medicine SET kind='保健品', name='辅酶Q10胶囊', image='http://t5wj9b45v.hn-bkt.clouddn.com/medicine/068.png', introduction='心脏动力素，熬夜护心', price=74.6 WHERE id=68;
UPDATE medicine SET kind='医疗器械', name='医用剪刀', image='http://t5wj9b45v.hn-bkt.clouddn.com/medicine/069.png', introduction='圆头防刺伤，不锈钢', price=16.8 WHERE id=69;
UPDATE medicine SET kind='防疫用品', name='垃圾袋', image='http://t5wj9b45v.hn-bkt.clouddn.com/medicine/070.png', introduction='医疗黄色，加厚 50×60cm', price=11.1 WHERE id=70;
UPDATE medicine SET kind='中药', name='灵芝孢子粉', image='http://t5wj9b45v.hn-bkt.clouddn.com/medicine/071.png', introduction='破壁≥99%，免疫调节', price=128.8 WHERE id=71;
UPDATE medicine SET kind='西药', name='维生素B族片', image='http://t5wj9b45v.hn-bkt.clouddn.com/medicine/072.png', introduction='熬夜族能量片，缓释技术', price=27.5 WHERE id=72;
UPDATE medicine SET kind='保健品', name='胶原蛋白面膜', image='http://t5wj9b45v.hn-bkt.clouddn.com/medicine/073.png', introduction='医用敷料级，术后修复', price=58.8 WHERE id=73;
UPDATE medicine SET kind='医疗器械', name='弹性绷带', image='http://t5wj9b45v.hn-bkt.clouddn.com/medicine/074.png', introduction='自粘不粘毛，运动护踝', price=13.9 WHERE id=74;
UPDATE medicine SET kind='防疫用品', name='紫外线灯', image='http://t5wj9b45v.hn-bkt.clouddn.com/medicine/075.png', introduction='38W 臭氧杀菌，遥控定时', price=109.0 WHERE id=75;
UPDATE medicine SET kind='中药', name='桂圆红枣茶', image='http://t5wj9b45v.hn-bkt.clouddn.com/medicine/076.png', introduction='补气血，姨妈期暖宫', price=26.6 WHERE id=76;
UPDATE medicine SET kind='西药', name='洛索洛芬钠贴', image='http://t5wj9b45v.hn-bkt.clouddn.com/medicine/077.png', introduction='肩痛腰痛，一贴止痛 12h', price=31.2 WHERE id=77;
UPDATE medicine SET kind='保健品', name='纳豆激酶胶囊', image='http://t5wj9b45v.hn-bkt.clouddn.com/medicine/078.png', introduction='疏通血管，日本进口', price=92.5 WHERE id=78;
UPDATE medicine SET kind='医疗器械', name='医用镊子', image='http://t5wj9b45v.hn-bkt.clouddn.com/medicine/079.png', introduction='尖头防滑，缝合拆线', price=9.7 WHERE id=79;
UPDATE medicine SET kind='防疫用品', name='84 消毒液', image='http://t5wj9b45v.hn-bkt.clouddn.com/medicine/080.png', introduction='5% 有效氯，1:1medicine_00 稀释', price=8.8 WHERE id=80;
UPDATE medicine SET kind='中药', name='薄荷叶茶', image='http://t5wj9b45v.hn-bkt.clouddn.com/medicine/081.png', introduction='清新口气，提神醒脑', price=17.7 WHERE id=81;
UPDATE medicine SET kind='西药', name='富马酸酮替芬片', image='http://t5wj9b45v.hn-bkt.clouddn.com/medicine/082.png', introduction='过敏性哮喘，睡前服', price=19.4 WHERE id=82;
UPDATE medicine SET kind='保健品', name='锌片', image='http://t5wj9b45v.hn-bkt.clouddn.com/medicine/083.png', introduction='儿童偏食，改善味觉', price=29.8 WHERE id=83;
UPDATE medicine SET kind='医疗器械', name='医用纱布块', image='http://t5wj9b45v.hn-bkt.clouddn.com/medicine/084.png', introduction='8 层脱脂，吸血不粘', price=10.5 WHERE id=84;
UPDATE medicine SET kind='防疫用品', name='免洗洗手液', image='http://t5wj9b45v.hn-bkt.clouddn.com/medicine/085.png', introduction='5medicine_00ml 家庭装，含甘油护手', price=16.6 WHERE id=85;
UPDATE medicine SET kind='中药', name='姜枣茶', image='http://t5wj9b45v.hn-bkt.clouddn.com/medicine/086.png', introduction='驱寒暖宫，手脚不冰凉', price=23.3 WHERE id=86;
UPDATE medicine SET kind='西药', name='铝碳酸镁片', image='http://t5wj9b45v.hn-bkt.clouddn.com/medicine/087.png', introduction='胃酸过多，嚼服柠檬味', price=14.2 WHERE id=87;
UPDATE medicine SET kind='保健品', name='褪黑素片', image='http://t5wj9b45v.hn-bkt.clouddn.com/medicine/088.png', introduction='倒班倒时差，0.5 mg 低剂量', price=25.5 WHERE id=88;
UPDATE medicine SET kind='医疗器械', name='医用棉签', image='http://t5wj9b45v.hn-bkt.clouddn.com/medicine/089.png', introduction='双头木棒，消毒上药', price=5.9 WHERE id=89;
UPDATE medicine SET kind='防疫用品', name='一次性鞋套', image='http://t5wj9b45v.hn-bkt.clouddn.com/medicine/090.png', introduction='加厚防滑，雨雪天也适用', price=9.3 WHERE id=90;
UPDATE medicine SET kind='中药', name='何首乌片', image='http://t5wj9b45v.hn-bkt.clouddn.com/medicine/091.png', introduction='乌发养发，泡酒煲汤', price=37.7 WHERE id=91;
UPDATE medicine SET kind='西药', name='双氯芬酸钠栓', image='http://t5wj9b45v.hn-bkt.clouddn.com/medicine/092.png', introduction='术后止痛，直肠给药', price=18.9 WHERE id=92;
UPDATE medicine SET kind='保健品', name='虾青素胶囊', image='http://t5wj9b45v.hn-bkt.clouddn.com/medicine/093.png', introduction='抗氧化之王，抗蓝光', price=87.3 WHERE id=93;
UPDATE medicine SET kind='医疗器械', name='急救毯', image='http://t5wj9b45v.hn-bkt.clouddn.com/medicine/094.png', introduction='金银双面，野外失温救命', price=12.8 WHERE id=94;
UPDATE medicine SET kind='防疫用品', name='空气消毒机', image='http://t5wj9b45v.hn-bkt.clouddn.com/medicine/095.png', introduction='等离子杀菌，静音卧室', price=199.0 WHERE id=95;
UPDATE medicine SET kind='中药', name='玫瑰花瓣茶', image='http://t5wj9b45v.hn-bkt.clouddn.com/medicine/096.png', introduction='疏肝解郁，姨妈好心情', price=28.4 WHERE id=96;
UPDATE medicine SET kind='西药', name='甲钴胺片', image='http://t5wj9b45v.hn-bkt.clouddn.com/medicine/097.png', introduction='修复神经，手脚麻木', price=22.0 WHERE id=97;
UPDATE medicine SET kind='保健品', name='低聚果糖', image='http://t5wj9b45v.hn-bkt.clouddn.com/medicine/098.png', introduction='益生元，通便不腹泻', price=41.6 WHERE id=98;
UPDATE medicine SET kind='医疗器械', name='医用口罩垫', image='http://t5wj9b45v.hn-bkt.clouddn.com/medicine/099.png', introduction='可替换垫片，延长口罩寿命', price=6.2 WHERE id=99;
#UPDATE medicine SET kind='防疫用品', name='洗手皂片', image='http://t5wj9b45v.hn-bkt.clouddn.com/medicine/medicine_100.png', introduction='纸型便携，露营出差神器', price=4.8 WHERE id=1medicine_00;