# Generated by Django 5.2.3 on 2025-09-14 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Medicine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kind", models.CharField(max_length=20)),
                ("name", models.CharField(max_length=20)),
                ("image", models.ImageField(upload_to="medicine_images/")),
                ("introduction", models.TextField()),
                ("price", models.FloatField()),
            ],
            options={
                "verbose_name": "药品",
                "verbose_name_plural": "药品",
                "db_table": "medicine",
            },
        ),
    ]
