# Generated by Django 5.2.3 on 2025-09-16 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop_app", "0002_comment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={"verbose_name": "评论", "verbose_name_plural": "评论"},
        ),
        migrations.AlterModelTable(
            name="comment",
            table="comment",
        ),
    ]
