# Generated by Django 5.2.3 on 2025-09-16 01:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop_app", "0003_alter_comment_options_alter_comment_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="medicine_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="shop_app.medicine",
            ),
        ),
    ]
