# Generated by Django 5.2.3 on 2025-09-16 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop_app", "0004_comment_medicine_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="avatar",
        ),
    ]
